"""add loads.accepted_at

Revision ID: ff3034541b4a
Revises: a3519fb54ee0
Create Date: 2026-08-16 20:36:25.189281

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff3034541b4a"
down_revision: str | Sequence[str] | None = "a3519fb54ee0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loads", sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loads", "accepted_at")
    # ### end Alembic commands ###
